manifest = "7576bd4fa059db42be448655d486365c9bb0125b12e4019d1c558fa10b229412"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.37.0" ]
revision = "382491ee558eb6ed57c07f89b4b2683d16302035"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.37.0" ]
revision = "1cce8dff4e3ef3520b0ce494097cc601383750ca"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.37.0" ]
revision = "9300904f6182bf0eef08ccc1f4a741e6adb05dd5"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.37.0" ]
revision = "e76146842ef3f36bed72c9087e459881af447bd6"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.37.0" ]
revision = "7ee93eef9bd8d83a44a07ba625b6310a038cba9f"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.37.0" ]
revision = "4302dffe038e23f3a4c130bae0a3fcc5c90483b0"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.37.0" ]
revision = "b110579f66cf68b517d2856ee20f66ada8ee42fe"
