targets = ["//:random"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.21.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
version = "1.21.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
version = "1.21.1"